# Generated by Django 2.1.14 on 2019-11-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avg1Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('ph', models.FloatField()),
                ('ohm', models.FloatField()),
                ('liter', models.FloatField()),
                ('celsius', models.FloatField()),
                ('camera', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Avg1Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('ph', models.FloatField()),
                ('ohm', models.FloatField()),
                ('liter', models.FloatField()),
                ('celsius', models.FloatField()),
                ('camera', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Avg5Minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('ph', models.FloatField()),
                ('ohm', models.FloatField()),
                ('liter', models.FloatField()),
                ('celsius', models.FloatField()),
                ('camera', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('ph', models.FloatField()),
                ('ohm', models.FloatField()),
                ('liter', models.FloatField()),
                ('celsius', models.FloatField()),
                ('camera', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
