# Generated by Django 2.1.14 on 2019-11-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='system',
            old_name='name',
            new_name='corporation',
        ),
        migrations.AddField(
            model_name='avg1hour',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='water.Source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avg1month',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='water.Source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avg5minute',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='water.Source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='original',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='water.Source'),
            preserve_default=False,
        ),
    ]
