# Generated by Django 2.1.14 on 2019-11-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_auto_20191125_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avg1Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('camera', models.CharField(max_length=4)),
                ('ph', models.FloatField()),
                ('ohm', models.FloatField()),
                ('liter', models.FloatField()),
                ('celsius', models.FloatField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.Source')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='original',
            index_together={('id', 'timestamp')},
        ),
    ]
