# Generated by Django 2.1.14 on 2019-11-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_auto_20191125_2009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='original',
            unique_together={('id', 'timestamp')},
        ),
        migrations.AlterIndexTogether(
            name='original',
            index_together=set(),
        ),
    ]
