# Generated by Django 2.1.14 on 2019-11-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_auto_20191125_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='water.Original')),
                ('ph', models.FloatField()),
                ('ohm', models.FloatField()),
                ('liter', models.FloatField()),
                ('celsius', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='avg1day',
            unique_together={('id', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='avg1hour',
            unique_together={('id', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='avg1month',
            unique_together={('id', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='avg5minute',
            unique_together={('id', 'timestamp')},
        ),
    ]
