# Generated by Django 2.1.14 on 2019-12-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_auto_20191203_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='celsius_offset',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='celsius_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='liter_offset',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='liter_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='ohm_offset',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='ohm_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='ph_offset',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='ph_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
