# Generated by Django 2.1.14 on 2019-12-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0007_auto_20191204_1546'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avg1day',
            unique_together={('source', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='avg1hour',
            unique_together={('source', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='avg1month',
            unique_together={('source', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='avg5minute',
            unique_together={('source', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='original',
            unique_together={('source', 'timestamp')},
        ),
    ]
