# Generated by Django 2.1.14 on 2019-12-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0008_auto_20191204_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avg1Day',
            new_name='Avg1Date',
        ),
    ]
